
# -- Required ------------------------------------------------------------------
version: 2

# -- build environment ---------------------------------------------------------
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

# -- conf location -------------------------------------------------------------
sphinx:
    configuration: docs/source/conf.py

# -- requirements --------------------------------------------------------------
python:
  install:
  - method: pip
    path: .
    extra_requirements:
      - doc
